cat << EOF > .env
APP_ID=${APP_ID}
PRIVATE_KEY=${PRIVATE_KEY}
WEBHOOK_SECRET=${WEBHOOK_SECRET}
WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
GHE_HOST=${GHE_HOST}
EOF

base64 -d <<< $PRIVATE_KEY > private-key.pem
